# $Header: $
#

Q=
ifeq ($(BUILD_TYPE),CLEAN)
.PHONY: all
all: clean
else
.PHONY: all
all: check_opt_change app
endif

#
# MAINDIR should be set to the relative path from this makefile directory
# to the base project directory.
#
MAINDIR = ../../../..
BASEDIR = $(MAINDIR)/base
MESSAGES_DIR = ../..

RAPIDJSON_INCDIR  = $(BASEDIR)/rapidjson-1.1.0/include
CATCH_INCDIR      = $(BASEDIR)/unit_test/Catch1-1.12.2/single_include
AGGREGATES_DIR    = $(MESSAGES_DIR)/Bct.Workflow.Aggregates.CPPLib
AGGREGATES_INCDIR = $(AGGREGATES_DIR)/include
AGGREGATES_SRCDIR = $(AGGREGATES_DIR)/src
RPN_INCDIR        = $(AGGREGATES_DIR)/BCT.RPNEvaluator.CPP/include
GENERATED_DIR     = $(MESSAGES_DIR)/Bct.Workflow.Aggregates.CPP.GeneratedCode
GENERATED_INCDIR  = $(GENERATED_DIR)/include
GENERATED_SRCDIR  = $(GENERATED_DIR)/src

TEST_INCDIR       = ../include
TEST_SRCDIR       = ../src

WARNFLAGS = -Wchar-subscripts -Wcomment -Wimplicit -Wparentheses -Wreturn-type -Wswitch -Wtrigraphs 

#ADDN_CPPFLAGS = 
#ADDN_CFLAGS = 
#ADDN_CXXFLAGS = 

ADDN_INCDIR = -I$(AGGREGATES_INCDIR) -I$(RPN_INCDIR) -I$(GENERATED_INCDIR) -I$(TEST_INCDIR) -I$(RAPIDJSON_INCDIR) -I$(CATCH_INCDIR)

include $(MAINDIR)/makefile.vxc_rtp

# Build the message libraries
#
$(GENERATED_SRCDIR)/generated_code_lib.a :
	@cd $(GENERATED_SRCDIR) && $(MAKE) -f makefile.vx CPU=$(CPU) BUILD_TYPE=$(BUILD_TYPE) COMDIR=$(COMDIR) RMSGDIR=$(RMSGDIR)

$(AGGREGATES_SRCDIR)/aggregates_lib.a :
	@cd $(AGGREGATES_SRCDIR) && $(MAKE) -f makefile.vx CPU=$(CPU) BUILD_TYPE=$(BUILD_TYPE) COMDIR=$(COMDIR) RMSGDIR=$(RMSGDIR)

#
# VPATH must include the relative pathnames (from the directory containing this
# makefile) to any directories containing source files used for the applications.
#

vpath AggAssess.cpp $(TEST_SRCDIR)
vpath AggNested.cpp $(TEST_SRCDIR)
vpath AssessMetaData.cpp $(TEST_SRCDIR)

#
# The following should define all of the source files of each type
# to be compiled for the executable
#
APP_NAME := unit_test
unit_test_dir = .
unit_test_cxx_files = \
AggAssess.cpp \
AggNested.cpp \
AssessMetaData.cpp \
AssessUnitTests.cpp \
AggNestedUnitTests.cpp \
CodeGenerationUnitTests.cpp \
QAComprehensiveUnitTests.cpp \
ComputeFieldUnitTests.cpp \
EnumFieldUnitTests.cpp \
GeneralUnitTests.cpp \
MetaUnitTests.cpp \
ReferenceAggregateUnitTests.cpp \
VersionChangeRuleUnitTests.cpp \
VectorFieldUnitTests.cpp

unit_test_libs = $(GENERATED_SRCDIR)/generated_code_lib.a $(AGGREGATES_SRCDIR)/aggregates_lib.a

include $(MAINDIR)/makefile.process_app_rtp

#
# This is the standard makefile for Taos applications
#
include $(MAINDIR)/makefile.build_apps_rtp
app : $(APP_LIST)

.PHONY: clean
clean::
	@cd  $(GENERATED_SRCDIR) && $(MAKE) -f makefile.vx CPU=$(CPU) BUILD_TYPE=$(BUILD_TYPE) COMDIR=$(COMDIR) RMSGDIR=$(RMSGDIR)
	@cd $(AGGREGATES_SRCDIR) && $(MAKE) -f makefile.vx CPU=$(CPU) BUILD_TYPE=$(BUILD_TYPE) COMDIR=$(COMDIR) RMSGDIR=$(RMSGDIR)
